[package]
name = "nya-sfx-stub"
version = "1.0.0"
edition = "2021"
description = "NYA self-extracting archive stub (extract-only)"
license = "MIT"

[[bin]]
name = "nya-sfx-stub"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "z"

[dependencies]
byteorder = "1.5"
lzma-rs = "0.3"
zstd = "0.12"
